### ISSUE TITLE
FullScan fails with NoHostAvailable

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#1123]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: 3.0.8

### Logs
* test_id: 83974595-7045-4c3c-914c-fe5cee3a173f

### Description

Seem like now that we report error of Fullscan correctly we are seeing them in 200gb-48h scenario 

![Screenshot from 2019-07-04 10-50-58](https://user-images.githubusercontent.com/340979/60649013-d384ae80-9e49-11e9-8f2b-e237ce02fea3.png)

### Steps to Reproduce

configure with:
```
run_fullscan: 'keyspace1.standard1, 5' # 'ks.cf|random, interval(min)''
```

**Expected behavior:** 
Fullscan to work

**Actual behavior:**

Fullscan fails with NoHostAvailable

**Comment by aleksbykov** [comment]
@fruch Do u have the sct.log? because there is no any logs in s3 and no any running instances
abykov@vdomresearchbox:~$ hydra investigate show-logs 83974595-7045-4c3c-914c-fe5cee3a173f
| Log links for testrun with test id 83974595-7045-4c3c-914c-fe5cee3a173f |
+------------------------------------+-------------------+
| Log type                           | Link              |
+------------------------------------+-------------------+
+------------------------------------+-------------------+
abykov@vdomresearchbox:~$ hydra list-resources --test-id 83974595-7045-4c3c-914c-fe5cee3a173f
No resources found on AWS
No resources found on GCE

**Comment by fruch** [comment]
it on scylla-staging/empty/longevity/longevity-200gb-4h on jenkins
I didn't had time to fetch the log out of this run.
