### ISSUE TITLE
sct debug: how can we run it standalone without avocado?

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla-cluster-tests#235]
Larisa wants to debug her new code in sct, how can we run it standalone without avocado?

**Comment by lmr** [comment]
Avocado does support running the test using the test files themselves, like:

    ./longevity_test.py

But it will use the avocado libraries, runtime and logging system, so I don't really see what is the point.  Avocado offers test logs and the code can be inspected using pdb if that's your thing. Also, all the code can be pylinted to avoid obvious mistakes, et cetera.

**Comment by lmr** [comment]
The code can be turned to be executed like a regular unittest as well. You just lose centralized logging, UI notifications and all that. So if she can elaborate more on why avocado itself is a hindrance, I'd be interested in hearing that.

**Comment by lmr** [comment]
I don't get why one needs to get rid of avocado in order to debug their tests, when avocado was developed precisely to help people developing and running tests.

**Comment by kongove** [comment]
The purpose of @larisau is reducing the test/debug time, I suggested her to skip node setup, reduce the number of db nodes, disable monitor.

**Comment by larisau** [comment]
I need to stop test, do some stuff (like generate coredump file), then to continue...

**Comment by kongove** [comment]
You can `stop` the test by a time.sleep(), or make the code to watch the corefile, continue the code if the core file is generated.  @larisau

**Comment by larisau** [comment]
Yes, that's what I did - currently there is no other choice

**Comment by lmr** [comment]
OK, I see the problem. Currently due to the multiprocessing architecture that avocado uses, using pdb from inside the tests (that are run as forked processes) is not supported right now. I started investigating what we can do to make it possible to debug the test subprocesses from inside avocado, so right now you have 2 options:

1) Add sleeps, like @akong mentioned
2) You can modify your test like:

```
diff --git a/longevity_test.py b/longevity_test.py
index b9356ce..b176e26 100644
--- a/longevity_test.py
+++ b/longevity_test.py
@@ -14,7 +14,7 @@
 # Copyright (c) 2016 ScyllaDB
 
 
-from avocado import main
+from unittest import main
 
 from sdcm.tester import ClusterTester
```
This will skip passing through the avocado runner machinery (untested on sct, I tested on simple instrumented avocado tests) and then you should be able to set tracepoints on pdb.

**Comment by lmr** [comment]
@larisau ^, please try that out and let me know if it solves this problem. As for me, I'm going to talk to the other avocado devs and see what we can do to provide users with pdb debugging out of the box. Ah, I forgot to mention, after you modify your test like mentioned above, you can run it stand alone, like:

```
python longevity_test.py
```

**Comment by ldoktor** [comment]
Hello guys, in order to debug running process(es) I'd recommend reading http://avocado-framework.readthedocs.io/en/latest/DevelopmentTips.html#remote-debug-with-eclipse I use this quite frequently, the only issue with that is when you need to debug the test's `__init__` it requires increasing the `early_status` timeout.

The usage is basically you just put `pydevd.settrace` everywhere you want to attach the process and it'll connect to your Eclipse. The only drawback is you have to use Eclipse, but hey, Eclipse is cool. You'll see.

**Comment by kongove** [comment]
@ldoktor Thanks, I just added a wiki page: https://github.com/scylladb/scylla-cluster-tests/wiki/Debug-Avocado-SCT
We can add more info there.
