### ISSUE TITLE
snitch_verify failed in artifact-tests

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#3667]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: 8513d38e3a6ad38538f9f58a4437ebf1bfebbbc4
* **scylla**: 4.6.dev-0.20210615.9d49a26e79

### Logs
* test_id: 0797f4f6-2874-4fcf-a763-55f8549ca01a
* job log: db-cluster: https://cloudius-jenkins-test.s3.amazonaws.com/0797f4f6-2874-4fcf-a763-55f8549ca01a/20210615_234629/db-cluster-0797f4f6.zip
* sct-runner: https://cloudius-jenkins-test.s3.amazonaws.com/0797f4f6-2874-4fcf-a763-55f8549ca01a/20210615_234629/sct-runner-0797f4f6.zip
* job link: https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-centos7-test/469/console

### Description

snitch_verify failed in all artifact-tests. We never assigned `endpoint_snitch` for artifact-tests, and the value is empty in scylla.yaml. But the expected value is `GoogleCloudSnitch`.

/Cc @KnifeyMoloko 

07:45:49  ----- LAST ERROR EVENT -------------------------------------------------------
07:45:49  2021-06-15 23:45:44.284: (TestFrameworkEvent Severity.ERROR), source=ArtifactsTest.test_scylla_service (artifacts_test.ArtifactsTest) [verify snitch against scylla.yaml configuration]() message=Traceback (most recent call last):
07:45:49  File "/jenkins/slave/workspace/scylla-master/artifacts/artifacts-centos7-test/scylla-cluster-tests/artifacts_test.py", line 108, in verify_snitch
07:45:49  self.assertTrue(any(snitch_matches_scylla_yaml),
07:45:49  AssertionError: False is not true : Expected snitch matches for scylla yaml to not be empty, but was. Snitch matches: [None]

### Steps to Reproduce

1. run artifact-tests with scylla-master

**Expected behavior:** [What you expected to happen]

verify_snitch passed

**Actual behavior:** [What actually happened]

07:45:49  File "/jenkins/slave/workspace/scylla-master/artifacts/artifacts-centos7-test/scylla-cluster-tests/artifacts_test.py", line 108, in verify_snitch
07:45:49  self.assertTrue(any(snitch_matches_scylla_yaml),
07:45:49  AssertionError: False is not true : Expected snitch matches for scylla yaml to not be empty, but was. Snitch matches: [None]

**Comment by amoskong** [comment]
@KnifeyMoloko do you expect the endpoint_snitch is set automatically?    at least for AMI?

We can assign `endpoint_snitch: GoogleCloudSnitch` in artifact-test configs, then SCT will config it in scylla.yaml in node_setup stage.

**Comment by KnifeyMoloko** [comment]
@amoskong The intention was to check the expected snitch type for every type of backend. Since the centos-7 test was running on GCE, this test expected 'GoogleCloudSnitch' as the used snitch type. In this case it's not that there is no snitch in scylla.yaml, it's actually set to SimpleSnitch. See the following log: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-artifacts/job/mc-artifacts-centos-8/7/console

"12:29:50  < t:2021-06-16 10:29:49,073 f:artifacts_test.py l:102  c:ArtifactsTest        p:INFO  > Snitch according to scylla.yaml: {'api_address': '127.0.0.1', 'api_doc_dir': '/opt/scylladb/api/api-doc/', 'api_port': 10000, 'api_ui_dir': '/opt/scylladb/swagger-ui/dist/', 'batch_size_fail_threshold_in_kb': 1024, 'batch_size_warn_threshold_in_kb': 128, 'cas_contention_timeout_in_ms': 1000, 'cluster_name': 'artifacts-centos8-jenkins-db-cluster-ab06bb2d', 'commitlog_segment_size_in_mb': 32, 'commitlog_sync': 'periodic', 'commitlog_sync_period_in_ms': 10000, 'commitlog_total_space_in_mb': -1, 'endpoint_snitch': 'SimpleSnitch', 'listen_address': '10.142.0.85', 'murmur3_partitioner_ignore_msb_bits': 12, 'native_shard_aware_transport_port': 19042, 'native_transport_port': 9042, 'num_tokens': 256, 'partitioner': 'org.apache.cassandra.dht.Murmur3Partitioner', 'read_request_timeout_in_ms': 5000, 'rpc_address': '10.142.0.85', 'rpc_port': 916"

The test failed because the regex matcher returned `None`.

I can fix this by adding 'SimpleSnitch' to the list of expected snitches (as a default). I'll also change the assertion message to be a bit more clear about what's failing.

**Comment by bentsi** [comment]
For Machine Images GCE and AWS the correct snitch is set by Scylla Machine Image service and that's what test checked

**Comment by KnifeyMoloko** [comment]
Waiting for 2 Jenkins runs to complete (1 with preinstalled scylla, 1 without) to complete, than we should be good to go.
