### ISSUE TITLE
Mocked test on PR failing (unable to load certificate)

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#4357]
I've seen it a few time on SCT PRs that the mocked tests are failing with the following
```
13:06:18  unable to load certificate
13:06:18  140527221237664:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: TRUSTED CERTIFICATE
```

https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-4351/3/execution/node/51/log/

**Comment by enaydanov** [comment]
Yeah, I saw this one time. But it was not reproduced on re-run. Need to collect more info about it.

**Comment by enaydanov** [comment]
We got it again and I was able to identify the root cause: it's a timing issue, and can be solved by adding some sleep before we try to use mock server.

It failed to read SSL certificate here:

https://github.com/scylladb/scylla-cluster-tests/blob/0059b0a2f7993792d67bb757fa12c1fd96789842/docker/env/hydra.sh#L333-L335

`openssl s_client ...` command failed and produced empty output which can't be parsed as a valid certificate.

So, @fruch, what do you think about adding `set -o pipefail` to the `hydra.sh` ?

**Comment by fruch** [comment]
> We got it again and I was able to identify the root cause: it's a timing issue, and can be solved by adding some sleep before we try to use mock server.
> 
> It failed to read SSL certificate here:
> 
> https://github.com/scylladb/scylla-cluster-tests/blob/0059b0a2f7993792d67bb757fa12c1fd96789842/docker/env/hydra.sh#L333-L335
> 
> `openssl s_client ...` command failed and produced empty output which can't be parsed as a valid certificate.
> 
> So, @fruch, what do you think about adding `set -o pipefail` to the `hydra.sh` ?

I don't care adding that

but why in the first place we are mocking setup in `hydra.sh` to begin with ? can't we do that as part of the test themselves ? the whole setup of them ?

**Comment by enaydanov** [comment]
> but why in the first place we are mocking setup in hydra.sh to begin with ? can't we do that as part of the test themselves ? the whole setup of them ?

There are 2 reasons:
1. We need to modify certifi's CA bundle before any Python code loads this module, so, it's better to do outside the Python code
2. We need to add lines to `/etc/hosts` and it's easier to do using docker's `--add-host` parameter.
