### ISSUE TITLE
[minor] `saslauthd_socket_path` should be used in OSS scylla

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#4502]
I've seen a few times warnings like this:
```
16:19:19  2022-03-02T09:46:07+00:00 perf-ycsb-latency-nemesis-ycsb-per-db-node-b47eb424-3 ! WARNING |  [shard 0] init - Unknown option : saslauthd_socket_path
```
we should be setting this configuration for OSS, only for enterprise (and only if ldap is configured)

**Comment by fgelcer** [comment]
@fruch , can you please share which branch you see it, logs where it can be found, or at what part of the code it is happening?

from what i see in the code related to it, it is only called inside one of the LDAP tests, and i don't see any reason for it to have this warning.

could it be that, `saslauthd_socket_path` is being set as `None` instead of not being set at all?

**Comment by fruch** [comment]
@fgelcer 

I think this if is wrong:

https://github.com/scylladb/scylla-cluster-tests/blob/0a87fda644f18773b617b226cd64a7146bb42c38/sdcm/provision/scylla_yaml/cluster_builder.py#L58
