### ISSUE TITLE
Cassandra-stress load was finished and printed result but the command returned status after 2 hours only

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#4808]
## Installation details

Kernel Version: 5.13.0-1022-aws
Scylla version (or git commit hash): `2022.1~rc5-20220515.6a1e89fbb` with build-id `5cecadda59974548befb4305363bf374631fc3e1`
Cluster size: 6 nodes (r5b.2xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-2022-1-db-node-d0d1290f-7 (52.31.86.119 | 10.0.0.23) (shards: 8)
- longevity-100gb-4h-2022-1-db-node-d0d1290f-6 (3.250.166.1 | 10.0.2.51) (shards: 8)
- longevity-100gb-4h-2022-1-db-node-d0d1290f-5 (34.243.154.19 | 10.0.2.99) (shards: 8)
- longevity-100gb-4h-2022-1-db-node-d0d1290f-4 (52.210.59.213 | 10.0.3.137) (shards: 8)
- longevity-100gb-4h-2022-1-db-node-d0d1290f-3 (54.246.175.242 | 10.0.3.121) (shards: 8)
- longevity-100gb-4h-2022-1-db-node-d0d1290f-2 (3.250.32.235 | 10.0.1.156) (shards: 8)
- longevity-100gb-4h-2022-1-db-node-d0d1290f-1 (54.194.138.9 | 10.0.0.74) (shards: 8)

OS / Image: `ami-02032eaf873ada3b0` (aws: eu-west-1)

Test: `longevity-100gb-4h-ebs-gp3-test`
Test id: `d0d1290f-fbbc-450b-8551-8906850d3026`
Test name: `enterprise-2022.1/longevity/longevity-100gb-4h-ebs-gp3-test`
Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/280c214cf2689f96954bf2f37f7d33daa651f86a/test-cases/longevity/longevity-100gb-4h.yaml)

## Issue description

Cassandra-stress load was finished and printed result at `17:48:21` but the command returned status at `19:38:58`:
```
< t:2022-05-22 17:48:21,422 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2022-05-22 17:48:21,422 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2022-05-22 17:48:21,422 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Results:
< t:2022-05-22 17:48:21,422 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Op rate                   :    8,354 op/s  [WRITE: 8,354 op/s]
< t:2022-05-22 17:48:21,422 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Partition rate            :    8,354 pk/s  [WRITE: 8,354 pk/s]
< t:2022-05-22 17:48:21,422 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Row rate                  :    8,354 row/s [WRITE: 8,354 row/s]
< t:2022-05-22 17:48:21,423 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Latency mean              :    9.5 ms [WRITE: 9.5 ms]
< t:2022-05-22 17:48:21,423 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Latency median            :    0.5 ms [WRITE: 0.5 ms]
< t:2022-05-22 17:48:21,423 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Latency 95th percentile   :    3.5 ms [WRITE: 3.5 ms]
< t:2022-05-22 17:48:21,423 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Latency 99th percentile   :  285.7 ms [WRITE: 285.7 ms]
< t:2022-05-22 17:48:21,423 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Latency 99.9th percentile : 1153.4 ms [WRITE: 1,153.4 ms]
< t:2022-05-22 17:48:21,424 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Latency max               : 9319.7 ms [WRITE: 9,319.7 ms]
< t:2022-05-22 17:48:21,424 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Total partitions          : 20,971,520 [WRITE: 20,971,520]
< t:2022-05-22 17:48:21,424 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Total errors              :          0 [WRITE: 0]
< t:2022-05-22 17:48:21,424 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Total GC count            : 0
< t:2022-05-22 17:48:21,424 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Total GC memory           : 0.000 KiB
< t:2022-05-22 17:48:21,424 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Total GC time             :    0.0 seconds
< t:2022-05-22 17:48:21,424 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Avg GC time               :    NaN ms
< t:2022-05-22 17:48:21,424 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > StdDev GC time            :    0.0 ms
< t:2022-05-22 17:48:21,424 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Total operation time      : 00:41:50
< t:2022-05-22 17:48:21,424 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2022-05-22 17:48:21,425 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > END



< t:2022-05-22 19:38:58,694 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > Failed to connect over JMX; not collecting these stats
< t:2022-05-22 19:38:58,748 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "echo TAG: loader_idx:0-cpu_idx:0-keyspace_idx:1; STRESS_TEST_MARKER=RWVX7XK8FI5NN6JJ4BOD; cassandra-stress write cl=QUORUM n=20971520 -schema keyspace=keyspace1 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=80 -pop seq=1..20971520 -col 'n=FIXED(10) size=FIXED(512)' -log interval=5 -node 10.0.0.74 -errors skip-unsupported-columns" finished with status 0
< t:2022-05-22 19:38:58,750 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-05-22 19:38:58.748: (CassandraStressEvent Severity.NORMAL) period_type=end event_id=da6a65fc-8840-414c-a0ac-482b6d3b0e25 duration=2h33m14s: node=Node longevity-100gb-4h-2022-1-loader-node-d0d1290f-1 [34.255.208.43 | 10.0.0.170] (seed: False)
< t:2022-05-22 19:38:58,750 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > stress_cmd=cassandra-stress write cl=QUORUM n=20971520 -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=80 -pop seq=1..20971520 -col 'n=FIXED(10) size=FIXED(512)' -log interval=5
< t:2022-05-22 19:38:58,765 f:longevity_test.py l:171  c:LongevityTest        p:INFO  > Prepare finished
```

All this time was no load.

![Screenshot from 2022-05-25 18-33-16](https://user-images.githubusercontent.com/34435448/170300847-bc2986f7-8033-4d67-a094-b428becdb23b.png)

- Restore Monitor Stack command: `$ hydra investigate show-monitor d0d1290f-fbbc-450b-8551-8906850d3026`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d0d1290f-fbbc-450b-8551-8906850d3026)
- Show all stored logs command: `$ hydra investigate show-logs d0d1290f-fbbc-450b-8551-8906850d3026`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/longevity/job/longevity-100gb-4h-ebs-gp3-test/4/)

**Comment by enaydanov** [comment]
Looks more like a problem with setting up the instance w/ EBS gp3 

## Installation details

Kernel Version: 5.13.0-1022-aws
Scylla version (or git commit hash): `2022.1~rc5-20220515.6a1e89fbb` with build-id `5cecadda59974548befb4305363bf374631fc3e1`
Cluster size: 6 nodes (r5b.2xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-2022-1-db-node-aa174e19-7 (63.35.195.190 | 10.0.1.203) (shards: 8)
- longevity-tls-50gb-3d-2022-1-db-node-aa174e19-6 (52.209.29.175 | 10.0.2.69) (shards: 8)
- longevity-tls-50gb-3d-2022-1-db-node-aa174e19-5 (54.217.20.112 | 10.0.1.71) (shards: 8)
- longevity-tls-50gb-3d-2022-1-db-node-aa174e19-4 (54.246.166.153 | 10.0.0.99) (shards: 8)
- longevity-tls-50gb-3d-2022-1-db-node-aa174e19-3 (52.48.190.8 | 10.0.0.39) (shards: 8)
- longevity-tls-50gb-3d-2022-1-db-node-aa174e19-2 (54.246.35.11 | 10.0.0.174) (shards: 8)
- longevity-tls-50gb-3d-2022-1-db-node-aa174e19-1 (52.49.207.164 | 10.0.1.12) (shards: 8)


OS / Image: `ami-02032eaf873ada3b0` (aws: eu-west-1)

Test: `longevity-50gb-3days-ebs-gp3-test`
Test id: `aa174e19-1c27-4eab-8979-8b04c75c5e72`
Test name: `enterprise-2022.1/longevity/longevity-50gb-3days-ebs-gp3-test`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/280c214cf2689f96954bf2f37f7d33daa651f86a/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

## Issue description

- Restore Monitor Stack command: `$ hydra investigate show-monitor aa174e19-1c27-4eab-8979-8b04c75c5e72`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=aa174e19-1c27-4eab-8979-8b04c75c5e72)
- Show all stored logs command: `$ hydra investigate show-logs aa174e19-1c27-4eab-8979-8b04c75c5e72`

## Logs:
- **db-cluster-aa174e19.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/aa174e19-1c27-4eab-8979-8b04c75c5e72/20220523_070010/db-cluster-aa174e19.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/aa174e19-1c27-4eab-8979-8b04c75c5e72/20220523_070010/db-cluster-aa174e19.tar.gz)
- **monitor-set-aa174e19.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/aa174e19-1c27-4eab-8979-8b04c75c5e72/20220523_070010/monitor-set-aa174e19.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/aa174e19-1c27-4eab-8979-8b04c75c5e72/20220523_070010/monitor-set-aa174e19.tar.gz)
- **loader-set-aa174e19.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/aa174e19-1c27-4eab-8979-8b04c75c5e72/20220523_070010/loader-set-aa174e19.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/aa174e19-1c27-4eab-8979-8b04c75c5e72/20220523_070010/loader-set-aa174e19.tar.gz)
- **sct-runner-aa174e19.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/aa174e19-1c27-4eab-8979-8b04c75c5e72/20220523_070010/sct-runner-aa174e19.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/aa174e19-1c27-4eab-8979-8b04c75c5e72/20220523_070010/sct-runner-aa174e19.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/longevity/job/longevity-50gb-3days-ebs-gp3-test/3/)

**Comment by fruch** [comment]
Seems like from the beginning the loader log is filled with errors like the following:
```
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write) 
```

I've seen similar issue with YCSB when there are too many errors it takes up ages to handle them, in this case seems that cassandra-stress keep spitting those errors, meaning it's still handling the processess/threads calling scylla (or at least the waiting for them to finish/timeout).

So 1) it's a bug in Cassandra-stress / java-driver, that it doesn't able to stop it's processes/threads, once the simulation is over.
and 2) we probably beating this setup with much more load then it can take, I think we should tune down the stress for those slow disk cases. with Nvme disk our bottleneck is the CPU, an we fine tuned the stress commands according to that. 

but seems like we are getting a storm of timeouts during the prepare stage (we also have nemesis during prepare, we should try without nemesis on prepare, so we might be able to check the specific nemesis for underlaying scylla issue)
![image](https://user-images.githubusercontent.com/340979/170865913-0fb9489e-28c6-4488-816a-81dce6491ae2.png)

**Comment by KnifeyMoloko** [comment]
Got a similar case in a recent `longevity-10gb-3h-gce-test`.  The c-s took 3h and printed results (in `sct.log`), but the threads went on until the end of the test.

## Installation details

Kernel Version: 5.13.0-1024-gcp
Scylla version (or git commit hash): `5.0~rc6-20220529.89a540d54` with build-id `cba9365aaf45042c6057bba3f7083446f614eab4`
Cluster size: 6 nodes (n1-highmem-16)

Scylla Nodes used in this run:
- longevity-10gb-3h-5-0-db-node-ba34688b-0-8 (34.138.196.234 | 10.142.0.11) (shards: 16)
- longevity-10gb-3h-5-0-db-node-ba34688b-0-7 (34.73.205.99 | 10.142.0.8) (shards: 16)
- longevity-10gb-3h-5-0-db-node-ba34688b-0-6 (34.74.105.129 | 10.142.0.229) (shards: 16)
- longevity-10gb-3h-5-0-db-node-ba34688b-0-5 (34.73.148.120 | 10.142.0.190) (shards: 16)
- longevity-10gb-3h-5-0-db-node-ba34688b-0-4 (35.196.141.16 | 10.142.0.74) (shards: 16)
- longevity-10gb-3h-5-0-db-node-ba34688b-0-3 (34.148.229.205 | 10.142.0.66) (shards: 16)
- longevity-10gb-3h-5-0-db-node-ba34688b-0-2 (34.73.84.10 | 10.142.0.41) (shards: 16)
- longevity-10gb-3h-5-0-db-node-ba34688b-0-1 (34.148.47.57 | 10.142.0.37) (shards: 16)


OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/6263987256348785937` (gce: us-east1)

Test: `longevity-10gb-3h-gce-test`
Test id: `ba34688b-7167-4871-bf22-78b405bf75cc`
Test name: `scylla-5.0/longevity/longevity-10gb-3h-gce-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1dc6f59d114784945d6d91cb24c1af604e274c57/test-cases/longevity/longevity-10gb-3h.yaml)

## Issue description

**>>>>>>>**
Got a similar case in a recent `longevity-10gb-3h-gce-test`.  The c-s took 3h and printed results (in `sct.log`), but the threads went on until the tested ended due to a timeout.

```
< t:2022-05-29 20:51:44,458 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-05-29 20:51:44.456: (CassandraStressEvent Severity.NORMAL) period_type=end event_id=86e032a3-8e2e-4831-9042-6b982a1f59af duration=4h25m0s: node=Node longevity-10gb-3h-5-0-loader-node-ba34688b-0-1 [35.231.225.216 | 10.142.0.230] (seed: False)
< t:2022-05-29 20:52:14,486 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-05-29 20:52:14.484: (CassandraStressEvent Severity.NORMAL) period_type=end event_id=e7cc55f5-47cd-42ad-bf3e-c55b43a840a5 duration=4h25m0s: node=Node longevity-10gb-3h-5-0-loader-node-ba34688b-0-2 [34.148.247.216 | 10.142.0.231] (seed: False)
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor ba34688b-7167-4871-bf22-78b405bf75cc`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ba34688b-7167-4871-bf22-78b405bf75cc)
- Show all stored logs command: `$ hydra investigate show-logs ba34688b-7167-4871-bf22-78b405bf75cc`

## Logs:
- **db-cluster-ba34688b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ba34688b-7167-4871-bf22-78b405bf75cc/20220529_204641/db-cluster-ba34688b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ba34688b-7167-4871-bf22-78b405bf75cc/20220529_204641/db-cluster-ba34688b.tar.gz)
- **monitor-set-ba34688b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ba34688b-7167-4871-bf22-78b405bf75cc/20220529_204641/monitor-set-ba34688b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ba34688b-7167-4871-bf22-78b405bf75cc/20220529_204641/monitor-set-ba34688b.tar.gz)
- **loader-set-ba34688b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ba34688b-7167-4871-bf22-78b405bf75cc/20220529_204641/loader-set-ba34688b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ba34688b-7167-4871-bf22-78b405bf75cc/20220529_204641/loader-set-ba34688b.tar.gz)
- **sct-runner-ba34688b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ba34688b-7167-4871-bf22-78b405bf75cc/20220529_204641/sct-runner-ba34688b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ba34688b-7167-4871-bf22-78b405bf75cc/20220529_204641/sct-runner-ba34688b.tar.gz)
- **parallel-timelines-report-ba34688b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ba34688b-7167-4871-bf22-78b405bf75cc/20220529_204641/parallel-timelines-report-ba34688b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ba34688b-7167-4871-bf22-78b405bf75cc/20220529_204641/parallel-timelines-report-ba34688b.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-10gb-3h-gce-test/14/)

**Comment by roydahan** [comment]
The first thing we should do here, is to reduce the stress threads in all ebs based longevities.
There is no way it will handle the same stress as the regular jobs.
(Cut it by at least half if not more than that, num of threads, check if it's round robin or not).

Second, we should check if the "-log interval=5" is relevant to the error messages printed to the log.
If it is, increase the interval to be 60.
If it doesn't and we still suffer from too many errors after decreasing the loads significantly, we may want to run the prepare with cl=ALL, no nemesis during prepare and "-errors ignore" for c-s.
