### ISSUE TITLE
performance_regression_alternator_test.py saves test results multiple times in the middle of a test

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla-cluster-tests#4980]
In performance_regression_alternator_test.py, the _workload() function if save_stats is true (and it is by default), saves the test results, which if I understand correctly (but please correct me if I'm wrong) includes things like the full monitoring data.

When I run SCT from my home network (with slow upload speeds), this step takes almost an hour.

My complaint in this issue is that an individual test in performance_regression_alternator_test.py calls _workload() multiple times. For example, write_test calls it three times. This means that the "stats saving" happens three times during the test. Is this necessary or useful? For example, if this includes saving the monitoring data (and I don't know if it does), the data saved after the third _workload() includes all the data saved in the two earlier runs?

CC @fruch

**Comment by fruch** [comment]
by design we save the result of each stage we are doing, it's not saving the whole monitoring data, but take a screenshots and snapshot to the time the last command run. it involved using webdriver to capture it from the grafana dashboard (in alternator we save 3 of those dashboards, the SCT one, the regular one and the alternator one)
we also upload the results of the test to Elasticsearch.

this whole collection of data wasn't designed to be run remotely (i.e. in a different network), and can be slow.

we need this information for the reports we are doing from those runs.

I'm guessing they can be optional, and code and a configuration can be added for doing that.

**Comment by nyh** [comment]
> by design we save the result of each stage we are doing, it's not saving the whole monitoring data, but take a screenshots and snapshot to the time the last command run. it involved using webdriver to capture it from the grafana dashboard (in alternator we save 3 of those dashboards, the SCT one, the regular one and the alternator one) we also upload the results of the test to Elasticsearch.
> 
> this whole collection of data wasn't designed to be run remotely (i.e. in a different network), and can be slow.

If it just connects to the monitoring node over port 3000 and takes a screenshot, this should be quick even over a remote network. What might explain the almost one hour I saw?

**Comment by fruch** [comment]
It should be much faster today when we are not using webdriver anymore
