### ISSUE TITLE
SCT docker backend is totally broken!

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla-cluster-tests#5155]
### Prerequisites

* [X ] Are you rebased to master ?
* [X] Is it reproducible ?
* [X ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**:  e7e4779d
* **scylla**: 2021.1.10

### Description
When trying to use docker backend and scylla perf test I encountered a problem with the scylla monitorin node if I use hydra which
is obvious (docker inside docker) and problems with running sct directly. I encountered a first problem with the monitor don't 
supporting my fedora distro (which make this unusable to 95% of scylla devs). After I added my distro I failed on  installing manager,
after I set 'use_mgmt' false I failed on 'operation not permited' in scylla node (fstream).
Log directory is attached below:
[sct_log_dir.tar.gz](https://github.com/scylladb/scylla-cluster-tests/files/9388917/sct_log_dir.tar.gz)

### Steps to Reproduce

1.Try to use docker backed for any test.

**Expected behavior:** Expected it to work

**Actual behavior:** It didn't work

**Comment by fruch** [comment]
@eliransin

1) docker within docker work fine, as long as we keep mounted paths identical to host
2) for docker backend support isn't full, and it's doesn't run a real "node" for monitoring, since monitoring stack itself is running on docker, cause of that reason docker backend doesn't support manager installation (which we by default install into the monitor node)
3) the only production job that uses docker backend, is the docker artifact tests (that run only one db node)

so given all this, we are not testing it regularly and can't guarantee  that any job would work ontop of it.

if you still want to invest time in fixing some of the things you've encountered, I'll be more then happy to review/merge them.

Anyhow I'm not sure how performance test ontop of local docker would be helpful, maybe I'm missing what exactly you are trying to test

**Comment by eliransin** [comment]
> Anyhow I'm not sure how performance test ontop of local docker would be helpful, maybe I'm missing what exactly you are trying to test

I use it as a rapid test development environment. If it is not supposed to work with docker, there should be an assert in the code
for the tests that shouldn't run on a docker backend or any other backend that is not suported. I personally think that this is not
necesairy.

> if you still want to invest time in fixing some of the things you've encountered, I'll be more then happy to review/merge them.

will do
