### ISSUE TITLE
Find best region or az before resources provision in AWS

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5201]
AWS has an api for showing recommended region or/and availability zone for given resources request:
https://docs.aws.amazon.com/cli/latest/reference/ec2/get-spot-placement-scores.html

Utilizing this api could help us minimizing spot termination and no-capacity errors in test.

**Comment by roydahan** [comment]
Not really, because we need to find the best AZ for the runner, loader and db nodes which are not the same instance type and may be different.
In addition, when starting the job it could be one AZ but after few hours / days it could non relevant anymore (both for provision new nodes and for spot termination).

For now, we don't need to handle this.

**Comment by soyacz** [comment]
Isn't it that we mostly hit spot termination on db nodes?

**Comment by roydahan** [comment]
Not necessarily.
