### ISSUE TITLE
Double grafana screenshots collection

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5588]
Longevity test collects Grafana screenshots during test teardown. This process is repeated also in `collect_logs` step in jenkins jobs.

It's not that cheap - it takes about 10 minutes.

We should drop one so we would save time&money.

**Comment by fruch** [comment]
during teardwon `get_grafana_screenshot_and_snapshot`, so it can populate the email data. (before we had argus)
since then there two new steps in the pipeline lines,

1) collect-logs
2) send email 

so collect-logs needs to update the `email_data.json`, but keep in mind there are special cases, like performance tests, that it might screw up the reports (need to test it specifically)

**Comment by soyacz** [comment]
I didn't validate if this still takes place and now it doesn't take 10 minutes.

**Comment by fruch** [comment]
> I didn't validate if this still takes place and now it doesn't take 10 minutes.

I think we can sum it up, as it's no more an issue
