### ISSUE TITLE
[k8s-functional] `_bring_cluster_back_to_original_state` fails to get cluster back

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5674]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

`test_nodetool_flush_and_reshard` k8s test leaves cluster in broken state sometimes. It makes the next test to fail (this case it was `test_operator_managed_tls`).

## Impact

Failed k8s test that is after this test requiring investigation. Example error:
```
cluster.ssl_context = ssl_context
>       with cluster.connect(wait_for_all_pools=True) as session:
functional_tests/scylla_operator/test_functional.py:799:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
cassandra/cluster.py:1733: in cassandra.cluster.Cluster.connect
???
cassandra/cluster.py:1769: in cassandra.cluster.Cluster.connect
???
cassandra/cluster.py:1756: in cassandra.cluster.Cluster.connect
???
cassandra/cluster.py:3572: in cassandra.cluster.ControlConnection.connect
???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
>   ???
E   cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'10.0.2.214:9142': ConnectionRefusedError(111, "Tried connecting to [('10.0.2.214', 9142)]. Last error: Connection refused")})
cassandra/cluster.py:3617: NoHostAvailable
```

## How frequently does it reproduce?

70% of times. But now workaround was applied: moved this test to the end (https://github.com/scylladb/scylla-cluster-tests/pull/5655/files).

## Installation details

Kernel Version: 5.4.226-129.415.amzn2.x86_64
Scylla version (or git commit hash): `5.2.0~dev-20230106.2612f98a6ccf` with build-id `067495c6f3768867382f4d482c9fdf0ef1e26d10`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.9.0-alpha.0-10-g36dd2bc
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: eu-north-1)

Test: `functional-eks`
Test id: `ed281cb5-4f1a-4f9f-8572-a886b0a87987`
Test name: `scylla-operator/operator-master/functional/functional-eks`
Test config file(s):

- [functional.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d9c6d81c70a79bfffadb53317a81c2ba9b2cace0/test-cases/scylla-operator/functional.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor ed281cb5-4f1a-4f9f-8572-a886b0a87987`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ed281cb5-4f1a-4f9f-8572-a886b0a87987)
- Show all stored logs command: `$ hydra investigate show-logs ed281cb5-4f1a-4f9f-8572-a886b0a87987`

## Logs:
- **db-cluster-ed281cb5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed281cb5-4f1a-4f9f-8572-a886b0a87987/20230108_020509/db-cluster-ed281cb5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed281cb5-4f1a-4f9f-8572-a886b0a87987/20230108_020509/db-cluster-ed281cb5.tar.gz)
- **sct-runner-ed281cb5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed281cb5-4f1a-4f9f-8572-a886b0a87987/20230108_020509/sct-runner-ed281cb5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed281cb5-4f1a-4f9f-8572-a886b0a87987/20230108_020509/sct-runner-ed281cb5.tar.gz)
- **loader-set-ed281cb5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed281cb5-4f1a-4f9f-8572-a886b0a87987/20230108_020509/loader-set-ed281cb5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed281cb5-4f1a-4f9f-8572-a886b0a87987/20230108_020509/loader-set-ed281cb5.tar.gz)
- **kubernetes-ed281cb5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed281cb5-4f1a-4f9f-8572-a886b0a87987/20230108_020509/kubernetes-ed281cb5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed281cb5-4f1a-4f9f-8572-a886b0a87987/20230108_020509/kubernetes-ed281cb5.tar.gz)
- **parallel-timelines-report-ed281cb5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed281cb5-4f1a-4f9f-8572-a886b0a87987/20230108_020509/parallel-timelines-report-ed281cb5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed281cb5-4f1a-4f9f-8572-a886b0a87987/20230108_020509/parallel-timelines-report-ed281cb5.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/functional/job/functional-eks/30/)
</details>

**Comment by vponomaryov** [comment]
I looked at the logs and I can say that the test `test_nodetool_flush_and_reshard` itself works ok and not guilty.
The problem is that the next one must have waited before the cluster becomes operational and it's rollout finishes.
The next test got the `no host available` problem just because we use pod IP addresses which get changed after a pod recreation.
And in current case there was ongoing Scylla pods recreation 1 by 1 during the next test.

So, the proper fix is to fix the logic that makes sure the cluster is operational in between the tests.

**Comment by fruch** [comment]
> I looked at the logs and I can say that the test `test_nodetool_flush_and_reshard` itself works ok and not guilty. The problem is that the next one must have waited before the cluster becomes operational and it's rollout finishes. The next test got the `no host available` problem just because we use pod IP addresses which get changed after a pod recreation. And in current case there was ongoing Scylla pods recreation 1 by 1 during the next test.
> 
> So, the proper fix is to fix the logic that makes sure the cluster is operational in between the tests:
> 
> * `_bring_cluster_back_to_original_state` method in the `functional_tests/scylla_operator/conftest.py` module.

question is what is the best way to do this logic

see the thread in:
https://github.com/scylladb/scylla-operator/pull/1108
 
there seems to be a big disagreement on how it should be done, the last suggest is waiting for CQL port to be open
on all nodes, that should be easy since we have the facility already in place

**Comment by vponomaryov** [comment]
All of it is not enough. We also should check that there is no triggered rollout in operator.
It is the situation happened in the test run used for this bug report. The rollout started happening during the next test.
So, need to check for absence of rollout, several times with intervals as well the general cluster readiness.

**Comment by fruch** [comment]
this is something I would expect the test do, i.e. to wait for the rollout to finish, otherwise what is it testing ?

**Comment by fgelcer** [comment]
> I looked at the logs and I can say that the test `test_nodetool_flush_and_reshard` itself works ok and not guilty. The problem is that the next one must have waited before the cluster becomes operational and it's rollout finishes.

i'm not very familiar with operator/k8s tests, but isn't it responsibility of the nemesis to end while leaving the cluster in a health format, instead of "next" one need to check if it is ok to start or not?

**Comment by vponomaryov** [comment]
@fruch @fgelcer 

Who said that the previous test did it? I didn't, I said it is not guilty because exactly the intermediate utility function called `_bring_cluster_back_to_original_state` triggered the new rollout by the scylla cluster spec update which gets done here: https://github.com/scylladb/scylla-cluster-tests/blob/328db417/functional_tests/scylla_operator/conftest.py#L166

And the problem is that it may trigger update for the silly spec updates, because we do huge dicts comparison just using python compare, which is not what we really need to do here.

Ok, it triggered redundant rollout, but it also didn't wait for it because of the race condition, it checked the cluster state too fast and exited.
This is what happened here.

So, the `_bring_cluster_back_to_original_state` function has problems in 2 places and exactly it must be fixed.

**Comment by soyacz** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/5741
