### ISSUE TITLE
hydra-show-monitor duration is not respected

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla-cluster-tests#5873]
https://jenkins.scylladb.com/job/QA-tools/job/hydra-show-monitor/465/parameters/

The duration is set to 30, help text says it's in minutes. The instance had been alive for several hours, I stopped it myself.

Instance id was i-0b4c0d49a016118f9 (sct-runner-1.6-restored-monitor-instance-b1dfb98c), here's the CPU utilization screenshot

![image](https://user-images.githubusercontent.com/4498177/222491658-c82dcc10-1548-4d37-a17a-0c86c34d772d.png)

**Comment by fruch** [comment]
First,

The deletion is done once an hour

This is the job, and it seems it's failing once in a while:
https://jenkins.scylladb.com/job/cloud-instance-stopper/

@yaronkaikov can we fix Munin, or be a bit more clear on where those job should be running ?

Also I need to verify, but the help text might be wrong (since the tags are in hours if I remember correctly)

**Comment by xemul** [comment]
> ... since the tags are in hours if I remember correctly

If it is, then the issue is about misleading text for sure :D

**Comment by fruch** [comment]
> > ... since the tags are in hours if I remember correctly
> 
> If it is, then the issue is about misleading text for sure :D

It's correct, it's in minutes.

We'll need to figure out the issue with the cleanup job failures. (It would have been cleaned up on one of the successful runs)

**Comment by fruch** [comment]
this is a bug in the cleanup job:
https://jenkins.scylladb.com/job/cloud-instance-stopper/

@scylladb/releng  would handle it

closing this one
