### ISSUE TITLE
[K8S] 14 tenant test timeout on setup of clusters 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6095]
While working on enabling sni proxy for the 14 tenants test cases

A run base on SCT master that timeout: 
https://argus.scylladb.com/test/37ffa9a1-870c-4858-8404-4cea2c335766/runs?additionalRuns[]=e02d9abf-8e61-4ff1-a74f-c96796c785a8

Last working run:
https://argus.scylladb.com/test/37ffa9a1-870c-4858-8404-4cea2c335766/runs?additionalRuns[]=abc8aebb-9279-4400-9469-ab9a1c375ab5

* Tried taking the image of the working run, didn't help
* Tried running with the stable v1.8.0 operator version didn't help
* Tried reverting a1f63c77fd59b6438a35d2415f5eb5a24947d183 and  d95ab1b89965df77b795eb84c562815298774d4e, also didn't helped

**Comment by vponomaryov** [comment]
At first, I found out that https://github.com/scylladb/scylla-cluster-tests/pull/6042 has changed the approach for creating K8S scylla pods.
Before we were creating and processing scylla pods by 1.
Now we create all the pods, wait for it and then process all of them in a narrow time range.
So, API call density got increased. Especially for multitenant case.

Then, I made it work the old way and ran a CI job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-12h-multitenant-eks/40/consoleFull
It passed the problematic point.
BUT, I haven't been able to reproduce it anymore.

Then, playing with it, I found out that some of threads (3-10 out of 14) hang on various steps inside of the `_create_node` method calls where we do lots of different stuff including API calls.

Then, I bumped the K8S version and the `vpc_cni` plugin for it. The same results.

Then, I tried to apply the API rate limiter for the EKS and it didn't help too.
Only increased spent time in places before the problematic point.

So, to me, it sounds like something has changed in the platform itself.

P.S. single cluster creation works if we merge the fix for yet another breakage: https://github.com/scylladb/scylla-cluster-tests/pull/6097

**Comment by fruch** [comment]
I've merged #6097, and we need to keep on this investigation...

**Comment by fruch** [comment]
I'm trying one more guess, reverting latest change to the hydra image, maybe there were changes there we didn't notices,
since whom introduced it did add the change to the `requirements.txt` to his PR

**Comment by fruch** [comment]
Seems like we still getting timeouts on create, no that often but still happening:
https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-scylla-operator-12h-multitenant-eks/52/

**Comment by fruch** [comment]
we haven't run this case for quite some time.

we'll reopen if we get to it
