### ISSUE TITLE
2 nemesis: NonDisruptive and Disruptive running on same node.

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-cluster-tests#6553]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master

### Logs
* test_id: 96a7d2d0-91a1-45a6-a853-2e383a82cb1d
* job log: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-schema-topology-changes-12h-test/9/
* argus: https://argus.scylladb.com/test/024e78ba-3671-4fd0-bafc-b48b2a978f59/runs?additionalRuns[]=96a7d2d0-91a1-45a6-a853-2e383a82cb1d

### Description

2 nemesises running on same node, was cause that 1 nemesis was failed.

1: disrupt_toggle_table_ics | longevity-parallel-topology-schema--db-node-96a7d2d0-5 | Failed | 2023-08-26 05:33:44 | 2023-08-26 05:34:08
2: disrupt_restart_with_resharding | longevity-parallel-topology-schema--db-node-96a7d2d0-5 | Succeeded | 2023-08-26 05:23:06 | 2023-08-26 05:34:53

_disrupt_toggle_table_ics_ start on node where still running disruptive nemesis _disrupt_restart_with_resharding_.

This cause the _disrupt_toggle_table_ics_ to failed with reset connection

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by fruch** [comment]
Assuming this time isn't part of the health checks,

How exactly was it causing it to fail ?
Please put here a bit more information that some would be able to work with.

**Comment by fruch** [comment]
seen again on 2024.1 runs

this nemesis failed to communicate with the node, since it was currently being drained
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5062, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2783, in disrupt_toggle_table_ics
    self.toggle_table_ics()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2500, in toggle_table_ics
    cur_compaction_strategy = get_compaction_strategy(node=self.target_node, keyspace=keyspace,
  File "/home/ubuntu/scylla-cluster-tests/test_lib/compaction.py", line 72, in get_compaction_strategy
    list_tables_compaction = node.run_cqlsh('SELECT keyspace_name, table_name, compaction FROM system_schema.tables',
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2741, in run_cqlsh
    cqlsh_out = self.remoter.run(cmd, timeout=timeout + 120,  # we give 30 seconds to cqlsh timeout mechanism to work
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: '/usr/bin/cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "SELECT keyspace_name, table_name, compaction FROM system_schema.tables" 10.12.11.155'

Exit code: 1

Stdout:



Stderr:

Connection error: ('Unable to connect to any servers', {'10.12.11.155:9042': ConnectionRefusedError(111, "Tried connecting to [('10.12.11.155', 9042)]. Last error: Connection refused")})

```
## Installation details

Kernel Version: 5.15.0-1051-aws
Scylla version (or git commit hash): `2024.1.0~rc2-20231217.f57117d9cfe3` with build-id `3a4d2dfe8ef4eef5454badb34d1710a5f36a859c`





Cluster size: 5 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- longevity-parallel-topology-schema--db-node-ed8036f8-9 (3.87.152.174 | 10.12.10.35) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-8 (54.175.186.140 | 10.12.8.136) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-7 (18.212.77.32 | 10.12.11.150) (shards: -1)
- longevity-parallel-topology-schema--db-node-ed8036f8-6 (34.229.144.208 | 10.12.8.58) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-5 (52.90.160.30 | 10.12.11.174) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-4 (3.88.29.47 | 10.12.9.120) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-3 (54.221.143.19 | 10.12.11.106) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-21 (54.242.56.62 | 10.12.8.192) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-20 (54.197.27.12 | 10.12.10.67) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-2 (54.166.137.111 | 10.12.8.179) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-19 (54.166.228.133 | 10.12.9.28) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-18 (3.87.96.84 | 10.12.11.175) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-17 (52.87.218.205 | 10.12.9.199) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-16 (54.196.133.112 | 10.12.8.12) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-15 (54.235.45.77 | 10.12.11.224) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-14 (54.91.126.133 | 10.12.8.189) (shards: -1)
- longevity-parallel-topology-schema--db-node-ed8036f8-13 (3.95.250.48 | 10.12.10.48) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-12 (54.85.27.68 | 10.12.11.155) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-11 (54.157.63.164 | 10.12.10.212) (shards: 7)
- longevity-parallel-topology-schema--db-node-ed8036f8-10 (54.87.1.160 | 10.12.11.21) (shards: -1)
- longevity-parallel-topology-schema--db-node-ed8036f8-1 (54.172.247.197 | 10.12.11.25) (shards: 7)


OS / Image: `ami-0514d67e24a1dae78` (aws: undefined_region)

Test: `longevity-schema-topology-changes-12h-test`
Test id: `ed8036f8-3bfa-4a44-9c9d-819227cab8b5`
Test name: `enterprise-2024.1/longevity/longevity-schema-topology-changes-12h-test`
Test config file(s):

- [longevity-parallel-schema-changes-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/3b954e543c7950520594e1f8df3e813efbe12fc3/test-cases/longevity/longevity-parallel-schema-changes-12h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor ed8036f8-3bfa-4a44-9c9d-819227cab8b5`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ed8036f8-3bfa-4a44-9c9d-819227cab8b5)
- Show all stored logs command: `$ hydra investigate show-logs ed8036f8-3bfa-4a44-9c9d-819227cab8b5`


## Logs:
- **db-cluster-ed8036f8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed8036f8-3bfa-4a44-9c9d-819227cab8b5/20231226_024557/db-cluster-ed8036f8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed8036f8-3bfa-4a44-9c9d-819227cab8b5/20231226_024557/db-cluster-ed8036f8.tar.gz)
- **sct-runner-events-ed8036f8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed8036f8-3bfa-4a44-9c9d-819227cab8b5/20231226_024557/sct-runner-events-ed8036f8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed8036f8-3bfa-4a44-9c9d-819227cab8b5/20231226_024557/sct-runner-events-ed8036f8.tar.gz)
- **sct-ed8036f8.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed8036f8-3bfa-4a44-9c9d-819227cab8b5/20231226_024557/sct-ed8036f8.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed8036f8-3bfa-4a44-9c9d-819227cab8b5/20231226_024557/sct-ed8036f8.log.tar.gz)
- **loader-set-ed8036f8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed8036f8-3bfa-4a44-9c9d-819227cab8b5/20231226_024557/loader-set-ed8036f8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed8036f8-3bfa-4a44-9c9d-819227cab8b5/20231226_024557/loader-set-ed8036f8.tar.gz)
- **monitor-set-ed8036f8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ed8036f8-3bfa-4a44-9c9d-819227cab8b5/20231226_024557/monitor-set-ed8036f8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ed8036f8-3bfa-4a44-9c9d-819227cab8b5/20231226_024557/monitor-set-ed8036f8.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2024.1/job/longevity/job/longevity-schema-topology-changes-12h-test/10/)
[Argus](https://argus.scylladb.com/test/e0d56457-6e58-49db-9f1e-ab59bfeab88a/runs?additionalRuns[]=ed8036f8-3bfa-4a44-9c9d-819227cab8b5)
</details>
