### ISSUE TITLE
Loaders are unused for extended period of time (I assume when the Scylla cluster is installed?)

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-cluster-tests#6973]
```
Dec 17 17:59:22 localhost.localdomain systemd-journal[101]: Runtime journal is using 8.0M (max allowed 390.8M, trying to leave 586.3M free of 3.8G available → current limit 390.8M).
...
Dec 17 17:59:36 rolling-upgrade--debian-buster-loader-node-fed55bfc-0-1 sudo[1314]: scylla-test : (command continued) systemctl stop sshd || true
                                                                                        sed -i "s/#PubkeyAuthentication \(.*\)$/PubkeyAuthentication yes/" /etc/ssh/sshd_config || true
                                                                                        sed -i -e "\$aPubkeyAcceptedAlgorithms +ssh-rsa" /etc/ssh/sshd_config || true
                                                                                        sed -i -e "\$aHostKeyAlgorithms +ssh-rsa" /etc/ssh/sshd_config || true
                                                                                        systemctl restart sshd || true
                                                                                    fi
                                                                                    systemctl restart sshd || true
```
Is the last line of initialization, then mostly idle until:
```
Dec 17 18:43:00 rolling-upgrade--debian-buster-loader-node-fed55bfc-0-1 sudo[3755]: scylla-test : TTY=unknown ; PWD=/home/scylla-test ; USER=root ; COMMAND=/bin/dd if=/dev/zero of=/var/sct_configured_swapfile bs=1M count=1024
```

If we are using spot, we just wasted ~45 minutes or so. Perhaps we can start it later in the process of tests?

(unsure how common it is for loaders to run on spot, get terminated, etc.)?

@fruch ?

**Comment by fruch** [comment]
In most case we get spot termination on the DB nodes

We deliberately split how SCT works into two phase, provisioning and then running the test (which configures all of the nodes, first DB, then loaders, then monitor.

so provision it later, won't gonna happen.

we were planning (for years now) of doing all the different cluster configuration in parallel, we are doing it on K8S, but not on VMs

anyhow in the test you are looking it it's a bit worse, since we are not using scylla image, but installing from RPMs, which is a longer process. 

we never use spot in rolling upgrade tests, they are 6-7h long

**Comment by roydahan** [comment]
This is how SCT is built.
It takes long time only for installations that aren't using images, which is rare test scenario.
Only for some rolling upgrades.
